### ISSUE TITLE
Suggestion on course resources.

### ISSUE THREAD

**Issue by kaiuri** [dpploy/chen-3170#30]
### About getting the tools

From the same initial assumptions of [00-syllabus.ipynb](https://github.com/dpploy/chen-3170/blob/master/notebooks/00-syllabus.ipynb), to avoid those famous *dependency issues* related to getting the suggested packages and software, It'd be a good idea to add the following package managers as suggestions for the not-so-die-hard-programmers:

On **Windows**:
- [Chocolatey](https://chocolatey.org/)

On **macOS**:
- [Homebrew](https://brew.sh/)

On **Linux**:
- **Nixpkgs**, for a sandbox approach.

### About Anaconda

On line [74](https://github.com/dpploy/chen-3170/blob/5d74367ab95699cffc2a39da6f178de8bb57e78b/notebooks/00-syllabus.ipynb?short_path=75e247f#L74) of [00-syllabus.ipynb](https://github.com/dpploy/chen-3170/blob/master/notebooks/00-syllabus.ipynb), it's suggested the students install Anaconda as a way of getting the Python-Jupyter resources.
I'd like to differ and recommend the smaller version of Anaconda, **Miniconda**, which is also readily available at [https://conda.io](https://conda.io).

Miniconda is considerably smaller than Anaconda and the user can add packages as they're need, where Anaconda has a much larger prepackaged toolchain which most of the time goes on unused.

### On the matter of the resources available.

Google offers two very capable free options to the ones already mentioned in line [72](https://github.com/dpploy/chen-3170/blob/1ee24a83e88c6f0f32db3107df2a4f2748370f25/notebooks/00-syllabus.ipynb?short_path=75e247f#L72) of [00-syllabus.ipynb](https://github.com/dpploy/chen-3170/blob/master/notebooks/00-syllabus.ipynb).

* [**Colaboratory**](https://colab.research.google.com/),
* [**Kaggle**](https://www.kaggle.com/)

Which have the following attributes.
* Production and execution of arbitrary python code through the browser,
* Both are especially well suited for:
   - machine learning,
   - data analysis and
   - education.

Technically, those are hosted Jupyter notebook services requiring no initial setup to use while providing free access to Google's computing resources including  CPUs, TPUs and GPUs through the web browser.

**Additionally** one might run those notebooks locally through  the `jupyter_http_over_ws` available at PyPl.

**Comment by dealmeidavf** [comment]
Great post. This would be best transferred to the course [Discussions](https://github.com/dpploy/chen-3170/discussions). Maybe more than one discussion category could capture parts of your suggestions.
Thanks Uriel.

--
Valmor
